<?php

namespace App\DataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use App\Entity\Carte;
use App\Entity\MissionBlanche;
use App\Entity\MissionBleue;
use App\Entity\Lumiere;
use App\Entity\Disgrace;
use App\Entity\DomaineReine;

class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $carte1= new Carte();
        $carte1->setFamille("Papillon");
        $carte1->setRole("Normal");
        $carte2= new Carte();
        $carte2->setFamille("Papillon");
        $carte2->setRole("Noble");
        $carte3= new Carte();
        $carte3->setFamille("Papillon");
        $carte3->setRole("Assassin");
        $carte4= new Carte();
        $carte4->setFamille("Papillon");
        $carte4->setRole("Protecteur");
        $carte5= new Carte();
        $carte5->setFamille("Papillon");
        $carte5->setRole("Espion");
        $carte6= new Carte();
        $carte6->setFamille("Crapaud");
        $carte6->setRole("Normal");
        $carte7= new Carte();
        $carte7->setFamille("Crapaud");
        $carte7->setRole("Noble");
        $carte8= new Carte();
        $carte8->setFamille("Crapaud");
        $carte8->setRole("Assassin");
        $carte9= new Carte();
        $carte9->setFamille("Crapaud");
        $carte9->setRole("Protecteur");
        $carte10= new Carte();
        $carte10->setFamille("Crapaud");
        $carte10->setRole("Espion");
        $carte11= new Carte();
        $carte11->setFamille("Rossignol");
        $carte11->setRole("Normal");
        $carte12= new Carte();
        $carte12->setFamille("Rossignol");
        $carte12->setRole("Noble");
        $carte13= new Carte();
        $carte13->setFamille("Rossignol");
        $carte13->setRole("Assassin");  
        $carte14= new Carte();
        $carte14->setFamille("Rossignol");
        $carte14->setRole("Protecteur");
        $carte15= new Carte();
        $carte15->setFamille("Rossignol");
        $carte15->setRole("Espion");
        $carte16= new Carte();
        $carte16->setFamille("Cerf");
        $carte16->setRole("Normal");
        $carte17= new Carte();
        $carte17->setFamille("Cerf");
        $carte17->setRole("Noble");
        $carte18= new Carte();
        $carte18->setFamille("Cerf");
        $carte18->setRole("Assassin");
        $carte19= new Carte();
        $carte19->setFamille("Cerf");
        $carte19->setRole("Protecteur");
        $carte20= new Carte();
        $carte20->setFamille("Cerf");
        $carte20->setRole("Espion");
        $carte21= new Carte();
        $carte21->setFamille("Lapin");
        $carte21->setRole("Normal");
        $carte22= new Carte();
        $carte22->setFamille("Lapin");
        $carte22->setRole("Noble");
        $carte23= new Carte();
        $carte23->setFamille("Lapin");
        $carte23->setRole("Assassin");
        $carte24= new Carte();
        $carte24->setFamille("Lapin");
        $carte24->setRole("Protecteur");
        $carte25= new Carte();
        $carte25->setFamille("Lapin");
        $carte25->setRole("Espion");
        $carte26= new Carte();
        $carte26->setFamille("Carpe");
        $carte26->setRole("Normal");
        $carte27= new Carte();
        $carte27->setFamille("Carpe");
        $carte27->setRole("Noble");
        $carte28= new Carte();
        $carte28->setFamille("Carpe");
        $carte28->setRole("Assassin");
        $carte29= new Carte();
        $carte29->setFamille("Carpe");
        $carte29->setRole("Protecteur");
        $carte30= new Carte();
        $carte30->setFamille("Carpe");
        $carte30->setRole("Espion");
        $manager->persist($carte1);
        $manager->persist($carte2);
        $manager->persist($carte3);
        $manager->persist($carte4);
        $manager->persist($carte5);
        $manager->persist($carte6);
        $manager->persist($carte7);
        $manager->persist($carte8);
        $manager->persist($carte9);
        $manager->persist($carte10);
        $manager->persist($carte11);
        $manager->persist($carte12);
        $manager->persist($carte13);
        $manager->persist($carte14);
        $manager->persist($carte15);
        $manager->persist($carte16);
        $manager->persist($carte17);
        $manager->persist($carte18);
        $manager->persist($carte19);
        $manager->persist($carte20);
        $manager->persist($carte21);
        $manager->persist($carte22);
        $manager->persist($carte23);
        $manager->persist($carte24);
        $manager->persist($carte25);
        $manager->persist($carte26);
        $manager->persist($carte27);
        $manager->persist($carte28);
        $manager->persist($carte29);
        $manager->persist($carte30);

        $missionBlanche1= new MissionBlanche();
        $missionBlanche1->setObjectif("Moins de papillon que le voisin de gauche");
        $missionBlanche2= new MissionBlanche();
        $missionBlanche2->setObjectif("Moins de crapaud que le voisin de gauche");
        $missionBlanche3= new MissionBlanche();
        $missionBlanche3->setObjectif("Moins de rossignol que le voisin de gauche");
        $missionBlanche4= new MissionBlanche();
        $missionBlanche4->setObjectif("Moins de cerf que le voisin de gauche");
        $missionBlanche5= new MissionBlanche();
        $missionBlanche5->setObjectif("Moins de lapin que le voisin de gauche");
        $missionBlanche6= new MissionBlanche();
        $missionBlanche6->setObjectif("Moins de carpe que le voisin de gauche");
        $missionBlanche7= new MissionBlanche();
        $missionBlanche7->setObjectif("Avoir au moins 3 noble");
        $missionBlanche8= new MissionBlanche();
        $missionBlanche8->setObjectif("Avoir au moins 2 assassin");
        $missionBlanche9= new MissionBlanche();
        $missionBlanche9->setObjectif("Avoir au moins 4 protecteur");
        $missionBlanche10= new MissionBlanche();
        $missionBlanche10->setObjectif("Avoir au moins 3 espion");
        $manager->persist($missionBlanche1);
        $manager->persist($missionBlanche2);
        $manager->persist($missionBlanche3);
        $manager->persist($missionBlanche4);
        $manager->persist($missionBlanche5);
        $manager->persist($missionBlanche6);
        $manager->persist($missionBlanche7);
        $manager->persist($missionBlanche8);
        $manager->persist($missionBlanche9);
        $manager->persist($missionBlanche10);

        $missionBleue1= new MissionBleue();
        $missionBleue1->setObjectif("La famille papillon est en disgrâce");
        $missionBleue2= new MissionBleue();
        $missionBleue2->setObjectif("La famille crapaud est en disgrâce");
        $missionBleue3= new MissionBleue();
        $missionBleue3->setObjectif("La famille rossignol est en disgrâce");
        $missionBleue4= new MissionBleue();
        $missionBleue4->setObjectif("La famille cerf est en disgrâce");
        $missionBleue5= new MissionBleue();
        $missionBleue5->setObjectif("La famille lapin est en disgrâce");
        $missionBleue6= new MissionBleue();
        $missionBleue6->setObjectif("La famille carpe est en disgrâce");
        $missionBleue7= new MissionBleue();
        $missionBleue7->setObjectif("Une carte de chaque famille doit être en disgrâce");
        $missionBleue8= new MissionBleue();
        $missionBleue8->setObjectif("Une famille doit avoir 5 cartes en disgrâce");
        $missionBleue9= new MissionBleue();
        $missionBleue9->setObjectif("3 familles maximum doivent être en lumière");
        $missionBleue10= new MissionBleue();
        $missionBleue10->setObjectif("2 famille minimum doivent être en disgrâce");
        $manager->persist($missionBleue1);
        $manager->persist($missionBleue2);
        $manager->persist($missionBleue3);  
        $manager->persist($missionBleue4);
        $manager->persist($missionBleue5);
        $manager->persist($missionBleue6);
        $manager->persist($missionBleue7);
        $manager->persist($missionBleue8);
        $manager->persist($missionBleue9);
        $manager->persist($missionBleue10);
       
        $manager->flush();
    }
}
